language: ruby

sudo: required

services:
  - docker

rvm:
  - 2.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

before_install:
  - bundle install
bundler_args: --without documentation development production
cache: bundler

script:
  - bundle exec rake
  - ./build
