#!/usr/bin/env ruby

lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'github/client'
require 'helicopter'
require 'yaml'

#
# 1. Send postcard to Github
#

# Env config for selected environment
env  = YAML.load_file('config.yml')[ENV['ENV'] || 'development']
# Github v3 API endpoint for wimdu repo
repo = Github::Client.new(secret: env['secret']).repos[env['repo']]
# Adds web hook to wimdu
hook = repo.web_hooks.add(env['hook'], events: ['pull_request'])

#
# 2. Refuel the helicopter
#

heli = Helicopter.new(on_pull: lambda do |id|
  puts repo.pulls[id].files.display
end)

#
# 3. Black Hawk Down
#

# Trap ^C and shutdown heli :'(
trap('INT') { heli.shutdown }
# Remove hook from repo on exit
at_exit { hook.delete }

#
# 3... 2... 1... GO!
#

heli.start
