#!/usr/bin/env ruby

lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'github/client'
require 'helicopter'

# To access all the stuff under /config
cfg = Helicopter.config

#
# 1. Send postcard to Github
#

# Github v3 API endpoint for wimdu repo
repo = Github::Client.new(secret: cfg.secret).repos[cfg.repo]
# Adds web hook to wimdu
hook = repo.web_hooks.add(cfg.hook, events: ['pull_request'])

#
# 2. Refuel the helicopter
#

heli = Helicopter.new(on_pull: lambda do |id|
  repo.pulls[id].files.each do |file|
    puts "#{file}: #{cfg.receivers_for(file)}"
  end
end)

#
# 3. Black Hawk Down
#

# Trap ^C and shutdown heli :'(
trap('INT') { heli.shutdown }
# Remove hook from repo on exit
at_exit { hook.delete }

#
# 3... 2... 1... GO!
#

heli.start
