github:
  repo: wimdu/wimdu
  secret: 0000000000000000000000000000000000000000
  hook: http://heli.wimdu.pagekite.me

groups:
  bi:
    - sebastian.katzer@wimdu.com

files:
  db/schema.rb: bi

notification:
  type: email
  from: pr-helicopter@wimdu.com
  subject: Detected changes for _file_
  body: _pr_ contains changes for _file_.

credentials:
  email:
    api_key: a12345678901234567A
    api_user: pr-helicopter
