github:
  repo: wimdu/wimdu
  secret: 7c821338f75137b54d9dd8b04d2d661c5031c250
  hook: http://heli.wimdu.pagekite.me

groups:
  bi:
    - sebastian.katzer@wimdu.com

files:
  db/schema.rb: bi
  app/models/seo_page.rb: bi

notification:
  type: base
  from: pr-helicopter@wimdu.com
  subject: Detected changes for _file_
  body: _pr_ contains changes for _file_.

email:
  api_key: a12345678901234567A
  api_user: pr-helicopter
