github:
  repo: wimdu/wimdu
  secret: 0000000000000000000000000000000000000000
  hook: http://heli.wimdu.pagekite.me

groups:
  bi:
    - sebastian.katzer@wimdu.com

files:
  db/schema.rb: bi

notification:
  type: base
  from: pr-helicopter@wimdu.com
  subject: _file_
  body: _pr_

credentials:
  base:
    api_key: a12345678901234567A
    api_user: pr-helicopter
